language: python

matrix:
  include:
    - python: 3.6
      env: NOXSESSION="lint"
    - python: 3.4
      env: NOXSESSION="unit-3.4"
    - python: 3.5
      env: NOXSESSION="unit-3.5"
    - python: 3.6
      env: NOXSESSION="unit-3.6"
    - python: 2.7
      env: NOXSESSION="unit-2.7"

install:
# Always install nox into Python 3, regardless of the Python version used.
- virtualenv -p python3 noxenv
- noxenv/bin/pip install nox

script: noxenv/bin/nox

notifications:
  email: false
