
name: Nox Tests

on:
  push:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup git submodule
        run: git submodule update --init --recursive

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup virtualenv
        run: |
          # Always install nox into Python 3, regardless of the Python version used.
          python3 -m venv noxenv
          noxenv/bin/pip install nox

      - name: Run lint
        run: |
          export NOXSESSION="lint"
          noxenv/bin/nox

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10', '3.11' ]

    name: Test Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup git submodule
        run: git submodule update --init --recursive

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup virtualenv
        run: |
          # Always install nox into Python 3, regardless of the Python version used.
          python3 -m venv noxenv
          noxenv/bin/pip install nox

      - name: Run nox tests
        run: |
          export NOXSESSION="unit-${{ matrix.python-version }}"
          noxenv/bin/nox
